name: Build, test and lint

permissions:
  contents: read

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: '1.27.1'
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.13.2
          install-only: true

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Configure git identity
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Run tests
        run: make test

      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
